name: flutter_application_4
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ðŸ“¦ Common dependencies
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  geolocator: ^12.0.0
  google_maps_flutter: ^2.5.0
  url_launcher: ^6.3.0  # âœ… For opening Google Maps links

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
